"""Add companies and annual_reports tables

Revision ID: 148cd1c66438
Revises: 8ade325ad4bc
Create Date: 2026-01-21 00:15:57.712613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '148cd1c66438'
down_revision = '8ade325ad4bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=True),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_scraped_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('annual_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('html_url', sa.String(length=500), nullable=True),
    sa.Column('view_url', sa.String(length=500), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('source_annual_report_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_reports_company_id', 'companies', ['company_id'], ['id'])
        batch_op.create_foreign_key('fk_reports_source_annual_report_id', 'annual_reports', ['source_annual_report_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reports_source_annual_report_id', type_='foreignkey')
        batch_op.drop_constraint('fk_reports_company_id', type_='foreignkey')
        batch_op.drop_column('source_annual_report_id')
        batch_op.drop_column('company_id')

    op.drop_table('annual_reports')
    op.drop_table('companies')
    # ### end Alembic commands ###
