"""Add user status, alerts and activity tracking

Revision ID: 9a3202c19019
Revises: f5f5d329851c
Create Date: 2026-02-20 23:29:13.133905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a3202c19019'
down_revision = 'f5f5d329851c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('table_name', sa.String(length=50), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('audit_log')
    op.drop_table('data_quality_metrics')
    op.drop_table('compliance_requirements')
    op.drop_table('access_controls')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('read_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('resolved_by')
        batch_op.drop_column('resolved_at')
        batch_op.drop_column('is_resolved')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('idx_users_email'))
        batch_op.drop_index(batch_op.f('idx_users_role'))
        batch_op.drop_index(batch_op.f('idx_users_username'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_users_username'), ['username'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_email'), ['email'], unique=False)
        batch_op.drop_column('last_login')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_resolved', sa.BOOLEAN(), server_default=sa.text('(FALSE)'), nullable=True))
        batch_op.add_column(sa.Column('resolved_at', sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('resolved_by', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['resolved_by'], ['id'])
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('read_at')
        batch_op.drop_column('is_read')
        batch_op.drop_column('user_id')

    op.create_table('access_controls',
    sa.Column('id', sa.NUMERIC(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('resource_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('access_level', sa.VARCHAR(length=20), nullable=False),
    sa.Column('granted_by', sa.INTEGER(), nullable=True),
    sa.Column('granted_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_reviewed', sa.TIMESTAMP(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'active'"), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_requirements',
    sa.Column('id', sa.NUMERIC(), nullable=True),
    sa.Column('standard_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('control_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('control_description', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('last_assessed', sa.TIMESTAMP(), nullable=True),
    sa.Column('assessed_by', sa.INTEGER(), nullable=True),
    sa.Column('evidence_link', sa.VARCHAR(length=255), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.CheckConstraint("status IN ('compliant', 'non_compliant', 'in_progress', 'not_applicable')"),
    sa.ForeignKeyConstraint(['assessed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_quality_metrics',
    sa.Column('id', sa.NUMERIC(), nullable=True),
    sa.Column('dataset_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('completeness_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('accuracy_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('consistency_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('timeliness_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('overall_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('checked_by', sa.INTEGER(), nullable=True),
    sa.Column('checked_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['checked_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.NUMERIC(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('action', sa.VARCHAR(length=100), nullable=False),
    sa.Column('table_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('record_id', sa.INTEGER(), nullable=True),
    sa.Column('old_value', sa.TEXT(), nullable=True),
    sa.Column('new_value', sa.TEXT(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('activities')
    # ### end Alembic commands ###
