"""Add compliance_keywords

Revision ID: f5f5d329851c
Revises: 148cd1c66438
Create Date: 2026-02-11 23:14:48.371379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5f5d329851c'
down_revision = '148cd1c66438'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annual_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compliance_keywords', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annual_reports', schema=None) as batch_op:
        batch_op.drop_column('compliance_keywords')

    # ### end Alembic commands ###
